### ISSUE TITLE
Expand Usage section in README

### ISSUE THREAD

**Issue by humphd** [TueNguyen2911/tue-1st-ssg#7]
You have some [usage examples](https://github.com/TueNguyen2911/tue-1st-ssg#how-to-use), but you don't really explain what they do, or how the args/flags work exactly.  Listing examples of how to run the program without any description isn't that useful.

Split these up and add explanations as to what is happening in each.

**Comment by TueNguyen2911** [comment]
Adding usage explanation at [commit a268e](https://github.com/TueNguyen2911/tue-1st-ssg/commit/a268e17497079c3ca871aa1feb4457dee12b5b90)
